### ISSUE TITLE
When clicked on inner circle, outer circle is changing.

### ISSUE THREAD

**Issue by samyadh** [luncheon/reinvented-color-wheel#1]
This is very rare usecase.
when we click on the inner circle especially the part which is marked in below screenshot, the outer circle is activated.

![image](https://user-images.githubusercontent.com/9761477/60725968-0321dc80-9f58-11e9-8220-6b14182a0d45.png)

**Comment by luncheon** [comment]
Thank you for reporting the issue.

I fixed it in v0.2.5.  
Could you please check if the problem is fixed?  
https://luncheon.github.io/reinvented-color-wheel/

**Comment by samyadh** [comment]
Yep! works perfect :)
