### ISSUE TITLE
Color picker (0.3.0) not working in Gatsby (3.0.1)

### ISSUE THREAD

**Issue by primozpadar** [luncheon/reinvented-color-wheel#10]
### Color picker does not work with SSR React pages.

Color picker version: **0.3.0**
Gatsby version: **3.0.1**
React version: **17.0.1**

### Build error message:
```shell
 ERROR #95312 

"window" is not available during server side rendering.

See our docs page for more info on this error: https://gatsby.dev/debug-html


  1 | export var onDrag = 
  2 | // for IE, Edge, Firefox, Chrome
> 3 | 'PointerEvent' in window ?
    | ^
  4 |     function (element, onDragStart, onDragMove) {
  5 |         element.addEventListener('pointerdown', function (event) {
  6 |             if (event.button === 0 && onDragStart(event) !== false) {
```

Probably it should check for typeof window somewhere in code like this:
```js
if (typeof window !== "undefined") {
  doSomething();
}

**Comment by luncheon** [comment]
@primozpadar
Thank you for your report. It reproduced.
I fixed to not use `window` without checking if it exists, and published v0.3.1.
Could you please check if the problem has been fixed?

**Comment by primozpadar** [comment]
I think it works properly now! 😄
I tried to build project with ```gatsby build``` and also ```gatsby develop``` and it works as it should.

**Comment by luncheon** [comment]
Thanks!
Closing.
