### ISSUE TITLE
Unminified version

### ISSUE THREAD

**Issue by srochapimenta** [luncheon/reinvented-color-wheel#18]
Hi, thanks for this great color well!

Im using it for light control over esp8266/esp32 with ws1812 led strip, i need to add a public property to allow set color like color.setrgb( x, x, x ),  also add range as same style as color well to allow dimming.

i have done some work on it, but minifyed version make it dificult to undertand, can u please share without minify ?

Ps. this is not an issue, just a request.

best regards.

**Comment by luncheon** [comment]
@srochapimenta 
Thanks for using it!

> i need to add a public property to allow set color like color.setrgb( x, x, x )

You can set the color using `color.rgb = [x, x, x]`.

----

> also add range as same style as color well to allow dimming.

What do you mean by this?

----

> can u please share without minify ?

Unminified version can be imported with the following code:

```js
import ReinventedColorWheel from "reinvented-color-wheel/es/reinvented-color-wheel.bundle.js";
```

or

```html
<script src="https://cdn.jsdelivr.net/npm/reinvented-color-wheel@0.4.0/iife/reinvented-color-wheel.js"></script>
```

You can explore the provided files in https://www.jsdelivr.com/package/npm/reinvented-color-wheel.
