### ISSUE TITLE
Angular app throwing error

### ISSUE THREAD

**Issue by samyadh** [luncheon/reinvented-color-wheel#2]
it's throwing error below.

ERROR in node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(5,36): error TS1005: ']' expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(5,46): error TS1131: Property or signature expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(5,52): error TS1005: ';' expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(6,5): error TS1128: Declaration or statement expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(6,18): error TS1109: Expression expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(7,5): error TS1128: Declaration or statement expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(7,18): error TS1109: Expression expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(8,5): error TS1128: Declaration or statement expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(8,18): error TS1109: Expression expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(9,5): error TS1128: Declaration or statement expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(9,28): error TS1109: Expression expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(10,5): error TS1128: Declaration or statement expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(10,29): error TS1109: Expression expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(11,5): error TS1128: Declaration or statement expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(11,29): error TS1109: Expression expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(12,5): error TS1128: Declaration or statement expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(12,38): error TS1109: Expression expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(13,5): error TS1128: Declaration or statement expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(13,23): error TS1109: Expression expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(14,1): error TS1128: Declaration or statement expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(42,26): error TS1005: ']' expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(42,28): error TS1068: Unexpected token. A constructor, method, accessor,
or property was expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(42,42): error TS1005: ';' expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(46,32): error TS1005: ';' expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(46,38): error TS1109: Expression expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(47,32): error TS1005: ';' expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(47,38): error TS1109: Expression expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(48,24): error TS1005: ',' expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(49,13): error TS1005: ';' expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(49,19): error TS1109: Expression expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(50,5): error TS1128: Declaration or statement expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(51,5): error TS1128: Declaration or statement expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(52,5): error TS1128: Declaration or statement expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(53,5): error TS1128: Declaration or statement expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(54,5): error TS1128: Declaration or statement expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(55,5): error TS1128: Declaration or statement expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(56,5): error TS1128: Declaration or statement expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(57,5): error TS1128: Declaration or statement expected.
node_modules/reinvented-color-wheel/es/reinvented-color-wheel.d.ts(58,1): error TS1128: Declaration or statement expected.

when we ng serve or ng build.

**Comment by luncheon** [comment]
I'm sorry for the inconvenience.  
I think it occurs with TypeScript < 3.5. (I have carelessly used new features of TypeScript 3.5.)  
I will fix it soon.

**Comment by luncheon** [comment]
I fixed it in v0.2.6!
