### ISSUE TITLE
Color Wheel (0.2.7)is not working on Angular 7

### ISSUE THREAD

**Issue by ram-kuchibhotla** [luncheon/reinvented-color-wheel#4]

**Comment by samyadh** [comment]
To Be specific it is only in EDGE browser. 
it throws "Object doesn't support this action"
TypeError: Object doesn't support this action at inverseTransform at onDragStart

**Comment by luncheon** [comment]
@samyadh
The Edge case is fixed on v0.2.8.

@Ramky9381
Is your issue the same as @samyadh's?

**Comment by ram-kuchibhotla** [comment]
> @samyadh
> The Edge case is fixed on v0.2.8.
> 
> @Ramky9381
> Is your issue the same as @samyadh's?

Hi Luncheon, thanks for the update. i just pullled your code. Its working fine. yeah its same. Thankks for the update.

**Comment by samyadh** [comment]
@luncheon you are awesome :)

**Comment by ram-kuchibhotla** [comment]
Hi Boss, Again facing same issue. responsiveness is not working again :(

**Comment by luncheon** [comment]
@Ramky9381
Really? Could you please tell me the browser and the browser version?  
Does it reproduce at https://luncheon.github.io/reinvented-color-wheel/test.html?

**Comment by ram-kuchibhotla** [comment]
Hi Luncheon, this issue has taken a new face. please chk the image attached
![wheel_Distort](https://user-images.githubusercontent.com/54663036/64036944-0ad5ba00-cb72-11e9-8be5-7ecc0c550f72.png)

**Comment by luncheon** [comment]
Thank you for taking the capture.  
And really sorry for not explaining this test page. I’m embarrassed😅
 
Actually, the captured shape looks fine.  
This page is for testing CSS transfoms, and the wheel shape is intentionally distorted.

So, forget that once, and please tell me about the broken responsiveness.  
How is the responsiveness implemented? CSS transforms?

**Comment by ram-kuchibhotla** [comment]
Hi  Lucheon Gud Evening, problem is with responsiveness only is not supported.,that too with the web application. tried to clear bt couldn't.

**Comment by ram-kuchibhotla** [comment]
Hi Luncheon, any update ? on the issue. Please revert back once with update.

**Comment by luncheon** [comment]
Hi, @Ramky9381, I'm really sorry but I didn’t understand your problem.  
Reverting doesn't solve the problem unless I reproduce the problem.

So I created a StackBlitz project with responsive color wheel component with Angular.  
https://stackblitz.com/edit/angular-epf5gm?file=src%2Fapp%2Fapp.component.ts

Is this responsive, right?

**Comment by ram-kuchibhotla** [comment]
Thankyou for responding. will chk and update you.

**Comment by fernandomacs** [comment]
Hi, @luncheon 
I am trying to implement the color wheel in angular, exactly like the image below. with the fields of RGB, HSV, hex, etc. I would like to have it working like the example, with the color wheel listening to the inputs and vice versa. I only have knowledge of Angular, and, I only found the complete example in react. In your Angular example, it just has the color wheel, without the inputs.

I got this far: https://stackblitz.com/edit/angular-fcrasa?file=src%2Fapp%2Fapp.component.ts
Still having some trouble with infinite loops and with the conversion to other formats (hsl, hex, etc).

Please, can you help me, by giving me some tips on how to get there? Thank you!

![image](https://user-images.githubusercontent.com/68201010/190928627-35f89525-a3d2-4347-b89b-7fb764c20d5c.png)

**Comment by luncheon** [comment]
@fernandomacs Thank you for trying to use reinvented-color-wheel.

First, Angular is too complex for the human race. It is safer not to use it. I strongly recommend not to use it.
But we all have our own circumstances. If you must use it, go ahead.
https://stackblitz.com/edit/angular-cupwum

**Comment by fernandomacs** [comment]
thanks, @luncheon! I will consider not using Angular in this case.

**Comment by fernandomacs** [comment]
Great, @luncheon thank you! I will consider changing to React.
About implementing fields with other formats, like HSL and hex, any tips?
https://stackblitz.com/edit/angular-cj6epa?file=src/app/app.component.ts

**Comment by luncheon** [comment]
@fernandomacs 
If you want to handle RGB, HSL, and HEX, it would be much easier to have the `AppComponent` directly hold the `ReinventedColorWheel` instance instead of wrapping it in the directive.
It seems like creating a directive would make it easier to reuse, but in fact it would be more complicated and harder to reuse than just holding an instance of `ReinventedColorWheel`.
https://stackblitz.com/edit/angular-qq2dtn?file=src%2Fapp%2Fapp.component.ts

**Comment by fernandomacs** [comment]
@luncheon That is exactly what I need. Now it's clear how to use it with other formats. Thank you!!!

**Comment by luncheon** [comment]
OK.
Again, Angular should not be used if possible. Many people regret it.
https://2021.stateofjs.com/en-US/libraries/front-end-frameworks/
