### ISSUE TITLE
sv-handle wrong position in hidden div

### ISSUE THREAD

**Issue by srnden** [luncheon/reinvented-color-wheel#8]
Hi. 
![image](https://user-images.githubusercontent.com/16322716/97170301-82b26b00-179c-11eb-86bd-92cef3c6818b.png)

https://codepen.io/srnden/pen/RwRpLwN

**Comment by luncheon** [comment]
Thanks! Try 0.2.10!

**Comment by srnden** [comment]
it's ok now, thx!
